# Generated by Django 5.2.8 on 2026-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('manager', 'MANAGER'), ('developer', 'DEVELOPER'), ('designer', 'DESIGNER'), ('tester', 'TESTER'), ('hr manager', 'HR MANAGER'), ('intern', 'INTERN'), ('software engineer', 'SOFTWARE ENGINEER'), ('data scientist', 'DATA SCIENTIST'), ('product manager', 'PRODUCT MANAGER'), ('business analyst', 'BUSINESS ANALYST'), ('devops engineer', 'DEVOPS ENGINEER'), ('system administrator', 'SYSTEM ADMINISTRATOR'), ('network engineer', 'NETWORK ENGINEER'), ('technical support', 'TECHNICAL SUPPORT'), ('it consultant', 'IT CONSULTANT'), ('other', 'OTHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('manager', 'MANAGER'), ('developer', 'DEVELOPER'), ('designer', 'DESIGNER'), ('tester', 'TESTER'), ('hr manager', 'HR MANAGER'), ('intern', 'INTERN'), ('software engineer', 'SOFTWARE ENGINEER'), ('data scientist', 'DATA SCIENTIST'), ('product manager', 'PRODUCT MANAGER'), ('business analyst', 'BUSINESS ANALYST'), ('devops engineer', 'DEVOPS ENGINEER'), ('system administrator', 'SYSTEM ADMINISTRATOR'), ('network engineer', 'NETWORK ENGINEER'), ('technical support', 'TECHNICAL SUPPORT'), ('it consultant', 'IT CONSULTANT'), ('other', 'OTHER')], max_length=200),
        ),
    ]
