# Generated by Django 5.2.4 on 2025-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'SICK'), ('annual', 'ANNUAL'), ('unpaid', 'UNPAID'), ('maternity', 'MATERNITY'), ('paternity', 'PATERNITY'), ('bereavement', 'BEREAVEMENT'), ('other', 'OTHER')], default='other', max_length=20),
        ),
    ]
