# Generated by Django 5.2.8 on 2025-11-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leaverequest_task_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Date_of_Birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employment_date',
            new_name='employment_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Position',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
