# Generated by Django 5.2.8 on 2026-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'SALES'), ('resarch & development', 'RESEARCH & DEVELOPMENT'), ('software development', 'SOFTWARE DEVELOPMENT'), ('product research', 'PRODUCT RESEARCH'), ('marketing', 'MARKETING'), ('human resource', 'HUMAN RESOURCE'), ('legal', 'LEGAL'), ('customer service', 'CUSTOMER SERVICE')], max_length=100),
        ),
    ]
