# Generated by Django 5.2.8 on 2026-02-04 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_leaverequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_currency',
            field=models.CharField(default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
